spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            maximum-pool-size: 15
            minimum-idle: 5
            idle-timeout: 30000

    thymeleaf:
        cache: false

    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

    mail:
        host: smtp.sina.com
        port: 465
        username: hhzpnewcoder@sina.com
        password: b1a2b25a85ab8b70
        protocol: smtps
        properties:
            mail:
                smtp.ssl.enable: true
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.newcoder.entity
    configuration:
        useGeneratedKeys: true    #回填id
        mapUnderscoreToCamelCase: true
server:
    port: 8088
    servlet:
        context-path: /community
logging:
    level:
      com.example.newcoder: debug

community:
    path:
        domain: http://localhost:8088
        upload: d:/work/data/upload

